Repository Cascadia-Connections/gybitg, pull requests merged in 2019-08, with the labels that each got.

#100 Added delete button and method for deletion of logged in user - Close #98
  gybitg/Controllers/ManageController.cs
  gybitg/Views/Manage/ManageNavPages.cs
  gybitg/Views/Manage/_ManageNav.cshtml
Labels: enhancement

#102 Account input validation keith - Close #99
  gybitg/Controllers/SearchController.cs
  gybitg/Models/ManageViewModels/AthleteProfileViewModel.cs
  gybitg/Models/ManageViewModels/AthleteStatsViewModel.cs
  gybitg/Models/ManageViewModels/CoachProfileViewModel.cs
  gybitg/Models/ManageViewModels/IndexViewModel.cs
  gybitg/Models/SearchViewModels/SearchResultsViewModel.cs
  gybitg/Models/SearchViewModels/SearchViewModel.cs
  gybitg/Views/Account/Login.cshtml
  gybitg/Views/Manage/EditAthleteProfile.cshtml
  gybitg/Views/Manage/Index.cshtml
Labels: enhancement

#104 Athelete profile grad date -keith - Close #103
  gybitg/Views/Account/_AthleteProfilePartial.cshtml
Labels: bug

#108 Search grad date keith
  gybitg/Controllers/SearchController.cs
Labels: bug

#110 New account reroute from login, to manage index - Close #101
  gybitg/Controllers/AccountController.cs
Labels: Refactor

#111 Basic/adv search fix close#109
  gybitg/Controllers/AccountController.cs
  gybitg/Controllers/CoachController.cs
  gybitg/Controllers/SearchController.cs
  gybitg/Models/SearchViewModels/SearchViewModel.cs
  gybitg/Views/Shared/_LoginPartial.cshtml
Labels: bug

#112 Athlete profile page close#88
  gybitg.Tests/SearchTests.cs
  gybitg/Controllers/AthleteController.cs
  gybitg/Controllers/CoachController.cs
  gybitg/Controllers/ManageController.cs
  gybitg/Controllers/SearchController.cs
  gybitg/Migrations/20190415190722_Initial.Designer.cs
  gybitg/Migrations/20190506184127_AthleteProfiles.Designer.cs
  gybitg/Migrations/20190506184127_AthleteProfiles.cs
  gybitg/Migrations/20190506202139_CoachProfiles.cs
  gybitg/Migrations/20190522200154_ChangeAthleteProfileDateTime.cs
  gybitg/Migrations/20190529232630_merge develop into 0520 branch.Designer.cs
  gybitg/Migrations/20190529232630_merge develop into 0520 branch.cs
  gybitg/Migrations/20190531010057_GalleryVideos model update.Designer.cs
  gybitg/Migrations/20190531010057_GalleryVideos model update.cs
  gybitg/Migrations/ApplicationDbContextModelSnapshot.cs
  gybitg/Models/ApplicationUser.cs
  gybitg/Models/ManageViewModels/AthleteUserViewModel.cs
  gybitg/Models/ManageViewModels/IndexViewModel.cs
  gybitg/Views/Athlete/Index.cshtml
  gybitg/Views/Coach/AthleteList.cshtml
  gybitg/Views/Manage/Index.cshtml
  gybitg/Views/Search/SearchResults.cshtml
  gybitg/gybitg.csproj
  gybitg/wwwroot/css/site.css
Labels: enhancement

#114 Update manage.index view close#113
  gybitg/Controllers/ManageController.cs
  gybitg/Views/Manage/Index.cshtml
Labels: Refactor

#115 Athlete follow button close#87
  gybitg/Controllers/CoachController.cs
  gybitg/Controllers/SearchController.cs
  gybitg/Views/Athlete/Index.cshtml
  gybitg/Views/Coach/AthleteList.cshtml
  gybitg/Views/Coach/Follow.cshtml
Labels: enhancement
