Repository Cascadia-Connections/gybitg, pull requests merged in 2019-06, with the labels that each got.

#76 Input validation keith - Close #60
  gybitg/Models/ManageViewModels/AthleteProfileViewModel.cs
  gybitg/Models/ManageViewModels/CoachProfileViewModel.cs
  gybitg/Models/ManageViewModels/IndexViewModel.cs
  gybitg/Models/SearchViewModels/SearchResultsViewModel.cs
  gybitg/Models/SearchViewModels/SearchViewModel.cs
  gybitg/Views/Manage/Index.cshtml
  gybitg/Views/Search/AdvancedSearch.cshtml
Labels: enhancement

#80 Fixed HSGradDate date time picker in EditAthleteProfile.cshtml
  gybitg/Views/Manage/EditAthleteProfile.cshtml
Labels: bug

#74 Fix athlete position enum close#66
  gybitg/Controllers/AccountController.cs
  gybitg/Controllers/ManageController.cs
  gybitg/Models/ManageViewModels/IndexViewModel.cs
  gybitg/Views/Manage/Index.cshtml
Labels: Refactor

#82 Added authorization to SearchController Close#68
  gybitg/Controllers/SearchController.cs
Labels: enhancement

#83 Final bug fix daniel
  gybitg.Tests/SearchTests.cs
  gybitg/Models/ManageViewModels/AthleteProfileViewModel.cs
Labels: bug
