Repository Cascadia-Connections/gybitg, pull requests merged in 2019-05, with the labels that each got.

#40 Search and link to Adv Search in Navbar Close #38
  gybitg/Controllers/SearchController.cs
  gybitg/Models/SearchViewModels/SearchViewModel.cs
  gybitg/Views/Shared/_LoginPartial.cshtml
Labels: enhancement

#51 migrations fix
  gybitg/Migrations/20190506202139_CoachProfiles.Designer.cs
  gybitg/Migrations/20190506202139_CoachProfiles.cs
Labels: bug

#57 Update Athlete DataTime stats Close #56
  gybitg/Models/Repositories/FakeAthleteRepository.cs
Labels: Refactor

#59 Search parameters keith
  gybitg/Models/AthleteProfile.cs
  gybitg/Models/SearchViewModels/SearchViewModel.cs
  gybitg/Views/Search/BasicSearch.cshtml
Labels: enhancement

#62 Register new username and email Close #50
  gybitg/Controllers/AccountController.cs
  gybitg/Views/Account/Register.cshtml
  gybitg/gybitg.csproj
Labels: enhancement

#69 Re log bug kevin
  gybitg/Controllers/AccountController.cs
Labels: bug
